### PR TITLE
Use _R_CHECK_LENGTH_1_CONDITION_ for .Renviron exercise

### PR DESCRIPTION
**Pull request by karawoo**
Since setting up a GitHub PAT is now part of the pre-workshop setup, I updated the .Renviron exercise to walk through setting `_R_CHECK_LENGTH_1_CONDITION_` and showing how it changes R's behavior. I did this with R-Ladies and it worked okay. We also talked about risks when doing this (i.e. if there are length > 1 conditions in code you don't control) and how to turn this back off if needed.

### CODE REVIEW

**Review by jimhester — APPROVED** [review]
LGTM!

**Comment by karawoo** [comment]
Will you merge, Jim? I don't have write access to this repo

**Comment by jimhester** [comment]
Oh, yes @jennybc should we make @karawoo part of this org so she has write access to all the projects?

**Comment by karawoo** [comment]
I am part of the org I think, but that doesn't automatically grant write access to all the repos

**Comment by jennybc** [comment]
I just added @karawoo to this repo.

You @jimhester and @karawoo have the same role org-wise, so I think the permissions just happened to be different for this (and perhaps other?) repo(s), due to history before we created this org.

@karawoo Speak up quickly whenever you discover a permission problem. I don't want that to create friction for you.

**Pull request merged**
